name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # npm ci needs a lockfile; create it if missing (first run only)
      - name: Ensure lockfile (first run only)
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi

      - name: Clean install (npm ci)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/
          if-no-files-found: error